"""Filesystem/asset helpers for the content builder."""

from __future__ import annotations

import os
import shutil
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

from tools.content_builder.constants import SITE_ORIGIN

ROOT = Path(__file__).resolve().parents[2]
CONTENT = ROOT / "content"
PUBLIC = ROOT / "public"
DIST = ROOT / "dist"
TEMPLATES = Path(__file__).resolve().parent / "templates"

def _env() -> Environment:
    return Environment(
        loader=FileSystemLoader(str(TEMPLATES)),
        autoescape=select_autoescape(["html", "xml"]),
    )


def _copy_public(dest: Path) -> None:
    """Copy public/ into dest (dest is replaced if it already exists)."""
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(
        PUBLIC,
        dest,
        ignore=shutil.ignore_patterns("sitemap.xml"),
    )


def _publish_dist(staging: Path, dist: Path) -> None:
    """Replace ``dist`` with ``staging`` via same-directory renames.

    ``os.replace`` cannot overwrite a non-empty directory, so the previous
    ``dist`` is moved aside first, then restored if the new tree cannot land.
    """
    dist = Path(dist)
    staging = Path(staging)
    dist.parent.mkdir(parents=True, exist_ok=True)
    backup = dist.parent / f".{dist.name}.bak-{os.getpid()}"
    if backup.exists():
        shutil.rmtree(backup)
    moved_aside = False
    try:
        if dist.exists():
            os.replace(dist, backup)
            moved_aside = True
        os.replace(staging, dist)
    except Exception:
        if moved_aside and backup.exists() and not dist.exists():
            os.replace(backup, dist)
        raise
    if backup.exists():
        shutil.rmtree(backup)


def _copy_content_images(dist: Path) -> None:
    """Copy content/{locale}/img/ → dist/{locale}/img/ for Markdown image URLs."""
    for locale_dir in sorted(CONTENT.iterdir()):
        if not locale_dir.is_dir() or locale_dir.name == "templates":
            continue
        src = locale_dir / "img"
        if not src.is_dir():
            continue
        dest = dist / locale_dir.name / "img"
        shutil.copytree(src, dest, dirs_exist_ok=True)


def _write_css_bundles(dist: Path) -> None:
    """One stylesheet per surface — avoids base-then-page second paint."""
    css_dir = dist / "css"
    base = (css_dir / "base.css").read_text(encoding="utf-8")
    header = "/* Generated by content_builder — edit public/css/ sources, not this file. */\n"
    bundles = {
        "site-root.css": base,
        "site-content.css": base + "\n" + (css_dir / "content.css").read_text(encoding="utf-8"),
        "site-landing-home.css": base
        + "\n"
        + (css_dir / "landing-home.css").read_text(encoding="utf-8"),
        "site-landing.css": base + "\n" + (css_dir / "landing.css").read_text(encoding="utf-8"),
    }
    for name, body in bundles.items():
        (css_dir / name).write_text(header + body, encoding="utf-8")



def _write(path: Path, html: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding="utf-8")



def _write_redirect(path: Path, target: str) -> None:
    """Tiny static redirect stub (works on any static host, including local)."""
    _write(
        path,
        (
            "<!doctype html>\n"
            f'<html lang="en"><head><meta charset="utf-8">'
            f'<meta http-equiv="refresh" content="0; url={target}">'
            f'<link rel="canonical" href="{SITE_ORIGIN}{target}">'
            f"<title>Redirecting…</title>"
            f"<script>location.replace({target!r})</script>"
            f'</head><body><p><a href="{target}">Continue</a></p></body></html>\n'
        ),
    )


