"""Build dist/: copy public assets, emit content HTML, write sitemaps."""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from html import escape
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

from tools.content_builder.chrome import chrome_for, language_menu
from tools.content_builder.parse import (
    ARTICLES_DIR,
    SITE_ORIGIN,
    VOTW_INDEX_STEM,
    WHATS_NEW_STEM,
    discover_article_pages,
    discover_core_pages,
    discover_votw_pages,
    discover_whats_new_pages,
    is_draft,
    parse_article_page,
    parse_core_page,
    parse_votw_page,
    parse_whats_new_page,
    recent_target_links,
    votw_links,
)
from tools.content_builder.sidebar import SOCIAL_LINKS
from tools.content_builder.sitemaps import write_sitemaps

ROOT = Path(__file__).resolve().parents[2]
CONTENT = ROOT / "content"
PUBLIC = ROOT / "public"
DIST = ROOT / "dist"
TEMPLATES = Path(__file__).resolve().parent / "templates"


def _env() -> Environment:
    return Environment(
        loader=FileSystemLoader(str(TEMPLATES)),
        autoescape=select_autoescape(["html", "xml"]),
    )


def _copy_public(dist: Path) -> None:
    if dist.exists():
        shutil.rmtree(dist)
    shutil.copytree(
        PUBLIC,
        dist,
        ignore=shutil.ignore_patterns("sitemap.xml"),
    )


def _copy_content_images(dist: Path) -> None:
    """Copy content/{locale}/img/ → dist/{locale}/img/ for Markdown image URLs."""
    for locale_dir in sorted(CONTENT.iterdir()):
        if not locale_dir.is_dir() or locale_dir.name == "templates":
            continue
        src = locale_dir / "img"
        if not src.is_dir():
            continue
        dest = dist / locale_dir.name / "img"
        shutil.copytree(src, dest, dirs_exist_ok=True)


def _write_css_bundles(dist: Path) -> None:
    """One stylesheet per surface — avoids base-then-page second paint."""
    css_dir = dist / "css"
    base = (css_dir / "base.css").read_text(encoding="utf-8")
    header = "/* Generated by content_builder — edit public/css/ sources, not this file. */\n"
    bundles = {
        "site-root.css": base,
        "site-content.css": base + "\n" + (css_dir / "content.css").read_text(encoding="utf-8"),
        "site-landing-home.css": base
        + "\n"
        + (css_dir / "landing-home.css").read_text(encoding="utf-8"),
        "site-landing.css": base + "\n" + (css_dir / "landing.css").read_text(encoding="utf-8"),
    }
    for name, body in bundles.items():
        (css_dir / name).write_text(header + body, encoding="utf-8")


def _lang_hrefs(locale: str) -> list[dict[str, str | bool]]:
    """Switching language goes to that locale's home. Locales are separate
    audiences, not translations of each other, so pages have no counterparts."""
    return language_menu(locale, lambda code: f"/{code}/")


def _write(path: Path, html: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding="utf-8")


def _canonical_url(page_path: str) -> str:
    return f"{SITE_ORIGIN}{page_path}"


def _normalize_href(href: str) -> str:
    href = href.strip()
    if href and not href.endswith("/"):
        href += "/"
    return href


def _title_with_level(title: str, level: str) -> str:
    """Site standard: CEFR level at the end of a link label (Title · A1)."""
    title = title.strip()
    level = level.strip()
    if not title or not level or title.endswith(level):
        return title
    return f"{title} · {level}"


def _plain_heading(heading_html: str) -> str:
    """Strip tags from page H1 HTML for use as a related-card label."""
    return re.sub(r"<[^>]+>", "", heading_html or "").strip()


def _enrich_related(
    related: list[dict[str, str]],
    pages_by_href: dict[str, dict[str, str]],
    *,
    source: str = "",
    draft_hrefs: set[str] | None = None,
    warn_draft_targets: bool = False,
) -> list[dict[str, str]]:
    """Label related cards: author title override, else target H1, then CEFR level."""
    if not related:
        return related
    draft_hrefs = draft_hrefs or set()
    where = f" in {source}" if source else ""
    enriched: list[dict[str, str]] = []
    for i, item in enumerate(related):
        entry = dict(item)
        href = _normalize_href(entry.get("href", ""))
        author_title = (entry.get("title") or "").strip()
        target = pages_by_href.get(href)
        if author_title:
            label = author_title
            level = (target or {}).get("level") or ""
        elif target:
            label = (
                (target.get("heading") or "").strip()
                or (target.get("title") or "").strip()
            )
            level = target.get("level") or ""
        else:
            print(
                f"warning: related[{i}]{where}: unresolved href {href!r} "
                f"(no title override and no matching content page); skipping",
                file=sys.stderr,
            )
            continue
        if not label:
            print(
                f"warning: related[{i}]{where}: href {href!r} resolved with "
                f"empty label; skipping",
                file=sys.stderr,
            )
            continue
        if warn_draft_targets and href in draft_hrefs:
            print(
                f"warning: related[{i}]{where}: href {href!r} points at a "
                f"draft page; the label resolves, but that URL is not emitted "
                f"without --drafts",
                file=sys.stderr,
            )
        entry["title"] = _title_with_level(label, level)
        enriched.append(entry)
    return enriched


def _render_page(
    template,
    page,
    votw_nav: dict[str, str],
    pages_by_href: dict[str, dict[str, str]] | None = None,
    *,
    source: str = "",
    draft_hrefs: set[str] | None = None,
    warn_draft_targets: bool = False,
) -> str:
    locale = page.locale
    related = _enrich_related(
        page.related,
        pages_by_href or {},
        source=source,
        draft_hrefs=draft_hrefs,
        warn_draft_targets=warn_draft_targets,
    )
    page.body_html = _expand_art_bands(page.body_html)
    page.tail_body_html = _expand_art_bands(page.tail_body_html)
    if page.show_hero_art:
        page.body_html = _place_title_hero(page.body_html, source=source or "")
        page.show_hero_art = False
    return template.render(
        page=page,
        chrome=chrome_for(locale),
        site_origin=SITE_ORIGIN,
        languages=_lang_hrefs(locale),
        canonical_url=_canonical_url(page.canonical_path),
        related=related,
        social_links=SOCIAL_LINKS,
        votw_href=votw_nav.get(locale),
    )


def _write_redirect(path: Path, target: str) -> None:
    """Tiny static redirect stub (works on any static host, including local)."""
    _write(
        path,
        (
            "<!doctype html>\n"
            f'<html lang="en"><head><meta charset="utf-8">'
            f'<meta http-equiv="refresh" content="0; url={target}">'
            f'<link rel="canonical" href="{SITE_ORIGIN}{target}">'
            f"<title>Redirecting…</title>"
            f"<script>location.replace({target!r})</script>"
            f'</head><body><p><a href="{target}">Continue</a></p></body></html>\n'
        ),
    )


_ART_BAND_MARKER_RE = re.compile(r"<!--\s*art:\s*band\s*-->", re.I)
_ART_HERO_MARKER_RE = re.compile(r"<!--\s*art:\s*hero\s*-->", re.I)
_FIRST_P_CLOSE_RE = re.compile(r"</p\s*>", re.I)

# Title hero band (default: after the first body paragraph).
_HERO_ART_HTML = """\
<div class="hero-art-slot" aria-hidden="true">
  <div class="hero-art">
    <div class="hero-art__arc"></div>
    <svg class="hero-art__flourish" viewBox="0 0 800 30" preserveAspectRatio="none" focusable="false">
      <path class="hero-art__stroke hero-art__stroke--warm" d="M-30 22 C 90 2, 190 34, 320 10 S 520 -2, 860 20"></path>
      <path class="hero-art__stroke hero-art__stroke--cool" d="M-20 14 C 150 32, 280 -2, 430 18 S 650 30, 860 6"></path>
      <circle class="hero-art__ring hero-art__ring--left" cx="110" cy="2" r="20"></circle>
      <circle class="hero-art__ring hero-art__ring--right" cx="670" cy="16" r="14"></circle>
      <path class="hero-art__stroke hero-art__stroke--fine" d="M 240 26 L 360 4 M 520 24 L 620 8"></path>
    </svg>
    <div class="hero-art__panel">
      <span class="hero-art__shape hero-art__shape--circle"></span>
      <span class="hero-art__shape hero-art__shape--bar"></span>
      <span class="hero-art__shape hero-art__shape--dot"></span>
    </div>
  </div>
</div>"""

# Mid-article decorative band (same language as the title hero, different marks).
_ART_BAND_HTML = """\
<div class="hero-art-slot" aria-hidden="true">
  <div class="hero-art hero-art--inline">
    <div class="hero-art__arc"></div>
    <svg class="hero-art__flourish" viewBox="0 0 800 30" preserveAspectRatio="none" focusable="false">
      <path class="hero-art__stroke hero-art__stroke--warm" d="M860 8 C 640 28, 520 -4, 380 20 S 160 34, -30 10"></path>
      <path class="hero-art__stroke hero-art__stroke--cool" d="M860 24 C 680 0, 540 32, 360 8 S 140 -2, -30 22"></path>
      <circle class="hero-art__ring hero-art__ring--left" cx="690" cy="4" r="18"></circle>
      <circle class="hero-art__ring hero-art__ring--right" cx="160" cy="22" r="12"></circle>
      <path class="hero-art__stroke hero-art__stroke--fine" d="M 480 4 L 580 26 M 220 6 L 300 24"></path>
    </svg>
  </div>
</div>"""


def _expand_art_bands(html: str) -> str:
    """Replace every <!-- art: band --> with the inline decorative band."""
    if not html or "art:" not in html.lower():
        return html
    return _ART_BAND_MARKER_RE.sub(_ART_BAND_HTML, html)


def _inject_hero_after_first_paragraph(html: str) -> str:
    """Place the title hero band after the first <p>, or at the top if none."""
    if not html:
        return _HERO_ART_HTML
    match = _FIRST_P_CLOSE_RE.search(html)
    if not match:
        return f"{_HERO_ART_HTML}\n{html}"
    at = match.end()
    return f"{html[:at]}\n{_HERO_ART_HTML}\n{html[at:]}"


def _place_title_hero(html: str, *, source: str = "") -> str:
    """Default: after the first <p>. Override with <!-- art: hero --> in the body."""
    if not html:
        return _HERO_ART_HTML
    markers = list(_ART_HERO_MARKER_RE.finditer(html))
    if not markers:
        return _inject_hero_after_first_paragraph(html)
    if len(markers) > 1 and source:
        print(
            f"warning: multiple <!-- art: hero --> in {source}; using the first",
            file=sys.stderr,
        )
    return _ART_HERO_MARKER_RE.sub(_HERO_ART_HTML, html, count=1)


def _list_marker_re(kind: str) -> re.Pattern[str]:
    """<!-- {kind}: list --> insert point for an automated content list."""
    return re.compile(rf"<!--\s*{re.escape(kind)}:\s*list\s*-->", re.I)


def _split_at_list_marker(
    html: str, kind: str, *, source: str = ""
) -> tuple[str, str] | None:
    """Split body on <!-- {kind}: list -->; None if the marker is missing.

    Only the first marker is used. Extra markers stay in the HTML and trigger
    a warning.
    """
    matches = list(_list_marker_re(kind).finditer(html))
    if not matches:
        return None
    if len(matches) > 1:
        where = f" in {source}" if source else ""
        print(
            f"warning: multiple <!-- {kind}: list -->{where}; using the first",
            file=sys.stderr,
        )
    match = matches[0]
    before = html[: match.start()].rstrip()
    after = html[match.end() :].lstrip()
    return before, after


def _content_list_html(
    aria_label: str, entries: list[dict[str, str]]
) -> str:
    """Shared dense link list used by VOTW series index and what’s-new.

    Date labels print only when the date changes from the previous row, so
    same-day items read as one block.
    """
    if not entries:
        return ""
    items: list[str] = []
    prev_date = None
    for entry in entries:
        kind = escape(entry["kind"]) if entry.get("kind") else ""
        raw_date = entry.get("date") or ""
        date = escape(raw_date) if raw_date else ""
        show_date = bool(date) and raw_date != prev_date
        if raw_date:
            prev_date = raw_date
        summary = escape(entry["summary"]) if entry.get("summary") else ""
        title = escape(entry["title"])
        date_html = (
            f'\n      <span class="content-list__date">{date}</span>'
            if show_date
            else ""
        )
        kind_html = (
            f'\n      <p class="content-list__kind">{kind}</p>' if kind else ""
        )
        summary_html = (
            f'\n      <p class="content-list__summary">{summary}</p>'
            if summary
            else ""
        )
        items.append(
            f'  <li class="content-list__item">\n'
            f'    <div class="content-list__row">\n'
            f'      <a class="content-list__link" href="{escape(entry["href"])}">'
            f'<span class="content-list__title">{title}</span></a>'
            f"{date_html}\n"
            f"    </div>"
            f"{kind_html}{summary_html}\n"
            f"  </li>"
        )
    return (
        f'<nav class="content-list" aria-label="{escape(aria_label)}">\n'
        f"<ul>\n"
        f"{chr(10).join(items)}\n"
        f"</ul>\n"
        f"</nav>\n"
    )


def _votw_list_html(locale: str, target: str, include_drafts: bool) -> str:
    """Lesson list for a series index, built from the files on disk."""
    links = votw_links(CONTENT, locale, target, include_drafts=include_drafts)
    entries = [
        {
            "href": link["href"],
            "title": _title_with_level(link["title"], link.get("level") or ""),
            "date": link.get("date") or "",
            "summary": link.get("description") or "",
        }
        for link in links
    ]
    return _content_list_html("Verb of the Week", entries)


def _whats_new_list_html(locale: str, target: str, include_drafts: bool) -> str:
    """What’s-new list: VOTW lessons + articles, newest first."""
    links = recent_target_links(
        CONTENT, locale, target, include_drafts=include_drafts
    )
    label = chrome_for(locale)["whats_new"]
    entries = [
        {
            "href": link["href"],
            "title": _title_with_level(link["title"], link.get("level") or ""),
            "kind": link.get("kind") or "",
            "date": link.get("date") or "",
            "summary": link.get("description") or "",
        }
        for link in links
    ]
    return _content_list_html(label, entries)


def _votw_nav_hrefs(series: list[tuple[str, str]]) -> dict[str, str]:
    """Where the header's VOTW item points, per locale, given the series
    indexes this build emits. A locale with none does not get the item."""
    by_locale: dict[str, list[str]] = {}
    for locale, target in sorted(series):
        by_locale.setdefault(locale, []).append(target)

    hrefs: dict[str, str] = {}
    for locale, targets in by_locale.items():
        if len(targets) > 1:
            print(
                f"warning: {locale} has VOTW series for {', '.join(targets)}; the "
                f"header can only point at one and uses {targets[0]!r}. Decide on a "
                f"hub page or per-target nav items",
                file=sys.stderr,
            )
        hrefs[locale] = f"/{locale}/{targets[0]}/votw/"
    return hrefs


def build(dist: Path = DIST, *, include_drafts: bool = False) -> int:
    env = _env()
    template = env.get_template("content_page.html")
    _copy_public(dist)
    _copy_content_images(dist)
    _write_css_bundles(dist)

    core_pages = [(parse_core_page(p, loc), p) for p, loc in discover_core_pages(CONTENT)]

    # Always parse for related-link labels; only emit non-drafts unless --drafts.
    draft_hrefs: set[str] = set()
    votw_pages = []
    votw_for_index = []
    for path, locale, target in discover_votw_pages(CONTENT):
        page = parse_votw_page(path, locale, target)
        votw_for_index.append(page)
        if is_draft(path):
            draft_hrefs.add(page.canonical_path)
            if not include_drafts:
                print(f"skip draft: {path.relative_to(CONTENT)}", file=sys.stderr)
                continue
            print(f"emit draft: {path.relative_to(CONTENT)}", file=sys.stderr)
        votw_pages.append((page, path, target))

    article_pages = []
    article_for_index = []
    for path, locale, target in discover_article_pages(CONTENT):
        page = parse_article_page(path, locale, target)
        article_for_index.append(page)
        if is_draft(path):
            draft_hrefs.add(page.canonical_path)
            if not include_drafts:
                print(f"skip draft: {path.relative_to(CONTENT)}", file=sys.stderr)
                continue
            print(f"emit draft: {path.relative_to(CONTENT)}", file=sys.stderr)
        article_pages.append((page, path, target))

    whats_new_pages = []
    whats_new_for_index = []
    for path, locale, target in discover_whats_new_pages(CONTENT):
        page = parse_whats_new_page(path, locale, target)
        whats_new_for_index.append(page)
        if is_draft(path):
            draft_hrefs.add(page.canonical_path)
            if not include_drafts:
                print(f"skip draft: {path.relative_to(CONTENT)}", file=sys.stderr)
                continue
            print(f"emit draft: {path.relative_to(CONTENT)}", file=sys.stderr)
        whats_new_pages.append((page, path, target))

    for page, path in core_pages:
        if is_draft(path):
            draft_hrefs.add(page.canonical_path)

    votw_nav = _votw_nav_hrefs(
        [
            (page.locale, target)
            for page, path, target in votw_pages
            if path.stem == VOTW_INDEX_STEM
        ]
    )
    pages_by_href: dict[str, dict[str, str]] = {}
    for page in (
        *[p for p, _path in core_pages],
        *votw_for_index,
        *article_for_index,
        *whats_new_for_index,
    ):
        pages_by_href[page.canonical_path] = {
            "heading": _plain_heading(page.heading_html),
            "title": page.title,
            "level": page.level,
        }
    warn_draft_targets = not include_drafts
    emitted = 0

    for page, path in core_pages:
        html = _render_page(
            template,
            page,
            votw_nav,
            pages_by_href,
            source=str(path.relative_to(CONTENT)),
            draft_hrefs=draft_hrefs,
            warn_draft_targets=warn_draft_targets,
        )
        # /en/contact/ → en/contact/index.html (plain static hosting)
        stem = path.stem
        out = dist / page.locale / stem / "index.html"
        _write(out, html)
        # Keep /en/contact.html working via a static redirect stub
        _write_redirect(dist / page.locale / f"{stem}.html", page.canonical_path)
        emitted += 1

    for page, path, target in votw_pages:
        locale = page.locale
        source = str(path.relative_to(CONTENT))
        series = dist / locale / target / "votw"
        if path.stem == VOTW_INDEX_STEM:
            # /en/learn-french/votw/ → en/learn-french/votw/index.html
            # List replaces <!-- votw: list --> (outside .article-body).
            lesson_list = _votw_list_html(locale, target, include_drafts)
            split = _split_at_list_marker(page.body_html, "votw", source=source)
            if split is None:
                print(
                    f"warning: missing <!-- votw: list --> in {source}; "
                    f"appending the lesson list after the body",
                    file=sys.stderr,
                )
                page.after_body_html = lesson_list
            else:
                page.body_html, page.tail_body_html = split
                page.after_body_html = lesson_list
            out = series / "index.html"
        else:
            # Flat: …/votw/slug/ → votw/slug/index.html
            # Nested: …/votw/lemma/job/ → votw/lemma/job/index.html
            under_votw = page.canonical_path.rstrip("/").split("/votw/", 1)[-1]
            out = series.joinpath(*under_votw.split("/")) / "index.html"
        _write(
            out,
            _render_page(
                template,
                page,
                votw_nav,
                pages_by_href,
                source=source,
                draft_hrefs=draft_hrefs,
                warn_draft_targets=warn_draft_targets,
            ),
        )
        emitted += 1

    for page, path, target in article_pages:
        # /en/learn-french/articles/slug/ → en/learn-french/articles/slug/index.html
        slug = page.canonical_path.rstrip("/").split("/")[-1]
        out = dist / page.locale / target / ARTICLES_DIR / slug / "index.html"
        _write(
            out,
            _render_page(
                template,
                page,
                votw_nav,
                pages_by_href,
                source=str(path.relative_to(CONTENT)),
                draft_hrefs=draft_hrefs,
                warn_draft_targets=warn_draft_targets,
            ),
        )
        emitted += 1

    for page, path, target in whats_new_pages:
        # /en/learn-french/whats-new/ → en/learn-french/whats-new/index.html
        # List replaces <!-- whats-new: list --> (outside .article-body).
        source = str(path.relative_to(CONTENT))
        lesson_list = _whats_new_list_html(page.locale, target, include_drafts)
        split = _split_at_list_marker(page.body_html, "whats-new", source=source)
        if split is None:
            print(
                f"warning: missing <!-- whats-new: list --> in {source}; "
                f"appending the lesson list after the body",
                file=sys.stderr,
            )
            page.after_body_html = lesson_list
        else:
            page.body_html, page.tail_body_html = split
            page.after_body_html = lesson_list
        out = dist / page.locale / target / WHATS_NEW_STEM / "index.html"
        _write(
            out,
            _render_page(
                template,
                page,
                votw_nav,
                pages_by_href,
                source=source,
                draft_hrefs=draft_hrefs,
                warn_draft_targets=warn_draft_targets,
            ),
        )
        emitted += 1

    sitemaps = write_sitemaps(dist)
    print(f"Emitted {emitted} content pages into {dist}")
    print(f"Wrote {len(sitemaps)} sitemap files")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(prog="python -m tools.content_builder")
    parser.add_argument(
        "--drafts",
        action="store_true",
        help="also emit pages marked draft: true (local builds only)",
    )
    args = parser.parse_args()
    return build(include_drafts=args.drafts)


if __name__ == "__main__":
    raise SystemExit(main())
