"""Generate a JS Unicode casefold helper that matches Python str.casefold().

Catalog search blobs are folded in Python; the client must fold the query the
same way so multilingual text filters agree (ß/ẞ → ss, etc.).

The content builder writes dist/js/unicode-casefold.js on every build from the
same interpreter that builds the index, so macOS/Linux Unicode-data differences
cannot desync a committed snapshot from CI.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT = ROOT / "public" / "js" / "unicode-casefold.js"

HEADER = (
    "/* Generated by tools.content_builder.casefold_js — do not edit by hand.\n"
    " * Matches Python str.casefold() for the interpreter that ran the generator.\n"
    " */\n"
)


def casefold_mapping() -> dict[int, str]:
    """Code points whose casefold form differs from the character itself."""
    mapping: dict[int, str] = {}
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        ch = chr(cp)
        folded = ch.casefold()
        if folded != ch:
            mapping[cp] = folded
    return mapping


def render_casefold_js(mapping: dict[int, str] | None = None) -> str:
    mapping = casefold_mapping() if mapping is None else mapping
    # Decimal keys keep the table compact and match JS number lookup.
    entries = ",".join(
        f"{cp}:{json.dumps(folded, ensure_ascii=False)}"
        for cp, folded in sorted(mapping.items())
    )
    return (
        f"{HEADER}"
        "(function (global) {\n"
        f"  const MAP = {{{entries}}};\n"
        "  global.PlumeraCaseFold = function caseFold(input) {\n"
        '    if (!input) return "";\n'
        "    let out = \"\";\n"
        "    for (const ch of String(input)) {\n"
        "      const cp = ch.codePointAt(0);\n"
        "      out += Object.prototype.hasOwnProperty.call(MAP, cp) ? MAP[cp] : ch;\n"
        "    }\n"
        "    return out;\n"
        "  };\n"
        "})(typeof globalThis !== \"undefined\" ? globalThis : window);\n"
    )


def write_casefold_js(path: Path = DEFAULT_OUT) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_casefold_js(), encoding="utf-8")
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=DEFAULT_OUT,
        help=f"Output path (default: {DEFAULT_OUT})",
    )
    args = parser.parse_args(argv)
    out = write_casefold_js(args.output)
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
